FROM public.ecr.aws/lambda/python:3.9

# Install unzip for lambda layer
RUN yum upgrade -y \
    && yum install unzip -y

# Only needed for local testing purposes
RUN pip install boto3 paramiko

# Copy function code
# LAMBDA_TASK_ROOT = /var/task
WORKDIR ${LAMBDA_TASK_ROOT}
COPY ssh.py .

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "ssh.handler" ]
